### ISSUE TITLE
Proposal: allow HTTP transport (roundtripper) to be parameterized

### ISSUE THREAD

**Issue by krish4good** [fabioberger/airtable-go#1]
First off, thanks for writing this API and open-sourcing it.

I was wondering if it makes sense to allow the transport of the HTTP client used by theimplementation to be parameterized. 

This allows for:

* automatic rate limiting by client. The RoundTripper implementation could automatically delay requests if more than 'm' concurrent requests are happening in the last 'n' seconds. 
* removal of API methods that exist only to allow the client to be stubbed. A custom RoundTripper can do whatever the heck it wants under the covers as long as it implements `RoundTrip()` correctly. IMO, this covers the testing use-case in a more idiomatic way than having to expose custom methods in the public interface used only for testing.

Let me know if this makes sense and I'll be happy to send a PR.

**Comment by fabioberger** [comment]
Thanks for opening this issue @krish4good! Please take a look at the PR I just opened to address it and please let me know if you have any more feedback!

**Comment by fabioberger** [comment]
Issue addressed in #2
